[theme]
primaryColor="#4F46E5"
backgroundColor="#000000"
secondaryBackgroundColor="#1F2937"
textColor="#FFFFFF"
font="sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
